language: java

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - /home/travis/.sonar/cache

addons:
  mariadb: '10.0'
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - mv unicorn_template.properties unicorn.properties
      
before_script:
  - chmod +x sonarqube.sh
  - ./sonarqube.sh

script: mvn test -B -V
