version: '3'
services:
  # handle database component
  dbserver:
    build:
      context: ./mysql-srv/
      dockerfile: ./Dockerfile
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    container_name: narwhal-dbserver
    volumes:
      - narwhaldbstorage:/var/lib/mysql 
  # handle manager component
  coordinator:
    build:
      context: ./narwhalcoordinator/
      dockerfile: ./Dockerfile
    environment:
      - DBPASSWD=${DATABASE_PASSWORD}
      - TOMCATUSER=${TOMCAT_USER}
      - TOMCATPASSWD=${TOMCAT_PASSWORD}
    container_name: narwhal-coordinator

  # handle tomcat server
  #tomcatserver:

  
volumes:
  # persistence for database
  narwhaldbstorage:
  # persistence for docker
  narwhalcommonstorage: