version: '3'
services:
  # handle database component
  dbserver:
    build:
      context: ./mysql-srv/
      dockerfile: ./Dockerfile
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    container_name: narwhal-dbserver
    volumes:
      - narwhaldbstorage:/var/lib/mysql 
  
  # handle manager component
  coordinator:
    build:
      context: ./narwhalcoordinator/
      dockerfile: ./Dockerfile
    environment:
      - DBPASSWD=${DATABASE_PASSWORD}
      - TOMCATUSER=${TOMCAT_USER}
      - TOMCATPASSWD=${TOMCAT_PASSWORD}
    container_name: narwhal-coordinator
    volumes:
      - narwhalconfigs:/home/configs

  # handle tomcat server
  tomcatserver:
    build: 
      context: ./tomcat-srv
      dockerfile: ./Dockerfile
    container_name: narwhal-tomcatsrv
    ports: 
      - 8888:8080
    volumes:
      - narwhalconfigs:/home/configs
  
  # handle maven builder
  mavenbuilder:
    build:
      context: ./mavenworker
      dockerfile: ./Dockerfile
    container_name: narwhal-mavenbuilder
    volumes:
      - narwhalconfigs:/home/configs
      - ${Unicorn_Directory}:/home/source

  
volumes:
  # persistence for database
  narwhaldbstorage:
  # storage for config files
  narwhalconfigs: