version: '3'
services:
  dbserver:
    image: 'mysql:latest'
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpassword
    container_name: unicorn-dbserver
    volumes:
      - narwhaldbstore:/var/lib/mysql
  
  databasefitter:
    build:
      context: .
      dockerfile: ./mysql-admin/Dockerfile
    depends_on:
      - dbserver
    links:
      - dbserver:databaselink

volumes:
  narwhaldbstore: