title: Unicorn
description: A platform for event processing in business process management

logo: /assets/images/unicorn_logo_lg_crop.png

baseurl: /Unicorn

include: ['_pages']

plugins:
  - jekyll-octicons

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
